# Generated by Django 5.2.8 on 2026-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
